# Site settings
title: Joel Wallis Jucá
description: >
  Web development thoughts, by Joel Wallis Jucá.
url: "http://joelwallis.github.io"
twitter_username: joelwallis1
github_username:  joelwallis

# Build settings
markdown: kramdown
