title: Joel Wallis Jucá
description: Sharing technical knowledge and opinions about software development.
url: "http://joelwallis.com"
twitter_username: joelwallis1
github_username:  joelwallis

# Build settings
encoding: utf-8
markdown: kramdown
timezone: America/Sao_Paulo
